// Code generated by MockGen. DO NOT EDIT.
// Source: internal/controller/recycle/restart/interface.go

// Package restart is a generated GoMock package.
package restart

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/alibaba/OpenSandbox/sandbox-k8s/apis/sandbox/v1alpha1"
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// TryRestart mocks base method.
func (m *MockHandler) TryRestart(ctx context.Context, pool *v1alpha1.Pool, pod *v1.Pod, opts *Spec) (*Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryRestart", ctx, pool, pod, opts)
	ret0, _ := ret[0].(*Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryRestart indicates an expected call of TryRestart.
func (mr *MockHandlerMockRecorder) TryRestart(ctx, pool, pod, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryRestart", reflect.TypeOf((*MockHandler)(nil).TryRestart), ctx, pool, pod, opts)
}
